window.LETS_WRENCH_REVIEWS = [
  { name: "Marcus T.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r01/88/88", text: "Brakes were grinding bad. They came to my apartment complex, had me done in under two hours. Fair price and zero runaround." },
  { name: "Linda R.", place: "Bellevue", avatar: "https://randomuser.me/api/portraits/women/24.jpg", text: "Battery died in a Bellevue parking lot during a cold snap. LetsWrench was out fast, tested everything, and got me running. Lifesaver." },
  { name: "James P.", place: "Papillion", avatar: "https://picsum.photos/seed/lw-r02/88/88", text: "Check engine light scared me. Explained the code in plain English, fixed what mattered, and didn't pile on extra stuff I didn't need." },
  { name: "Sarah M.", place: "Omaha", avatar: "https://randomuser.me/api/portraits/men/12.jpg", text: "Oil change in my driveway before work. Showed up on time, clean work, and the quote matched the final bill. That's rare." },
  { name: "Danny K.", place: "La Vista", avatar: "https://picsum.photos/seed/lw-r03/88/88", text: "Alternator went out at work. Fixed it in the lot so I didn't miss my shift. Super professional and fast." },
  { name: "Rachel H.", place: "Council Bluffs", avatar: "https://randomuser.me/api/portraits/women/38.jpg", text: "Did a pre-purchase inspection on a truck I was buying. Saved me from a money pit. Worth every penny." },
  { name: "Mike S.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r04/88/88", text: "Called after hours with a no-start. 24/7 isn't just marketing — someone actually answered and showed up. Grateful." },
  { name: "Patricia W.", place: "Elkhorn", avatar: "https://randomuser.me/api/portraits/men/31.jpg", text: "Starter replacement at home. Quote upfront, done same day, and my husband's truck starts perfect now." },
  { name: "Carlos G.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r05/88/88", text: "Honest mechanic. Told me my brakes could wait another month when another shop said emergency. That earned my trust." },
  { name: "Jennifer L.", place: "Bellevue", avatar: "https://randomuser.me/api/portraits/women/52.jpg", text: "We run a small cleaning business with three vans. LetsWrench handles our fleet and always works around our schedule." },
  { name: "Tom B.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r06/88/88", text: "18+ years shows. Diagnosed a weird noise in ten minutes that two shops couldn't figure out. Fixed it right there." },
  { name: "Amy C.", place: "Papillion", avatar: "https://randomuser.me/api/portraits/men/45.jpg", text: "Tune-up and spark plugs in the driveway. Car runs smoother and MPG went up. Already booked my husband's SUV." },
  { name: "Robert N.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r07/88/88", text: "Recommended to my neighbor and my brother. All three of us happy. That's how you know they're legit." },
  { name: "Kelly D.", place: "La Vista", avatar: "https://randomuser.me/api/portraits/women/63.jpg", text: "Dealership wanted double for the same brake job. Mobile service was easier and way more reasonable." },
  { name: "Steve F.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r08/88/88", text: "Radiator hose blew on I-80. They met me off the highway and got me safe to drive home. Above and beyond." },
  { name: "Michelle A.", place: "Bellevue", avatar: "https://randomuser.me/api/portraits/men/58.jpg", text: "Texted a photo of the leak, got a quote back quick. Showed up next morning and fixed it before the kids' school run." },
  { name: "Brian E.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r09/88/88", text: "Serpentine belt shredded in a grocery store lot. Had a new one on and was back shopping in about an hour." },
  { name: "Diana J.", place: "Papillion", avatar: "https://randomuser.me/api/portraits/women/74.jpg", text: "Wheel bearing was humming bad. Replaced on-site, test drove with me after. Quiet as new." },
  { name: "Greg O.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r10/88/88", text: "Local guys who know Nebraska weather and what it does to cars. You can tell they've been doing this forever." },
  { name: "Natalie V.", place: "Council Bluffs", avatar: "https://randomuser.me/api/portraits/men/71.jpg", text: "Came to my job site and worked on my work truck during lunch. Didn't have to take a day off. Huge help." },
  { name: "Chris Z.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r11/88/88", text: "Topped off fluids, checked belts, and caught a worn hose before it popped. Preventive stuff most places skip." },
  { name: "Heather Q.", place: "Bellevue", avatar: "https://randomuser.me/api/portraits/women/82.jpg", text: "Thermostat and coolant flush in the driveway. No shop waiting room, no Uber home. Just done." },
  { name: "Tony M.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r12/88/88", text: "Won't use anyone else now. Fair, fast, and they actually pick up the phone. Five stars every time." },
  { name: "Vanessa R.", place: "La Vista", avatar: "https://randomuser.me/api/portraits/men/79.jpg", text: "A/C died in July. They came out same day and had cold air again before dinner. Can't thank them enough." },
  { name: "Eric H.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r13/88/88", text: "Used them for my daughter's first car inspection. Walked us through everything like family. No pressure." },
  { name: "Sandra K.", place: "Papillion", avatar: "https://randomuser.me/api/portraits/women/89.jpg", text: "Flat tire and dead battery same morning. One trip, both handled in my office parking garage." },
  { name: "Justin W.", place: "Bellevue", avatar: "https://picsum.photos/seed/lw-r14/88/88", text: "Quick text quote, fair price, done in my driveway while I worked from home. How it should be." },
  { name: "Maria L.", place: "Omaha", avatar: "https://randomuser.me/api/portraits/men/86.jpg", text: "Solo mom — really appreciated clear pricing and not being talked down to. Car runs great." },
  { name: "David P.", place: "Elkhorn", avatar: "https://picsum.photos/seed/lw-r15/88/88", text: "Fleet of four delivery vehicles. They keep us on the road without killing our schedule." },
  { name: "Angela S.", place: "Omaha", avatar: "https://randomuser.me/api/portraits/women/17.jpg", text: "Check engine was a loose gas cap situation but they still scanned for free and showed me the readout. Honest." },
  { name: "Ryan T.", place: "La Vista", avatar: "https://picsum.photos/seed/lw-r16/88/88", text: "Brake job at 8pm because I couldn't drive another day. True 24/7 service." },
  { name: "Kim B.", place: "Bellevue", avatar: "https://randomuser.me/api/portraits/men/93.jpg", text: "Third time using LetsWrench. Consistent every single visit." },
  { name: "Oscar M.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r17/88/88", text: "Fixed my work van behind our shop. Didn't lose a day of income." },
  { name: "Hannah F.", place: "Papillion", avatar: "https://randomuser.me/api/portraits/women/28.jpg", text: "Explained what failed on my alternator with photos. Felt informed, not sold to." },
  { name: "Trevor J.", place: "Council Bluffs", avatar: "https://picsum.photos/seed/lw-r18/88/88", text: "Came across the river from Council Bluffs — still came out, still fair on price. Respect." },
  { name: "Brenda C.", place: "Omaha", avatar: "https://randomuser.me/api/portraits/men/21.jpg", text: "My elderly dad's car — patient, kind, and left everything cleaner than they found it." },
  { name: "Luke A.", place: "La Vista", avatar: "https://picsum.photos/seed/lw-r19/88/88", text: "Suspension clunk diagnosed in minutes. Parts same day. Solid." },
  { name: "Nicole D.", place: "Bellevue", avatar: "https://randomuser.me/api/portraits/men/36.jpg", text: "Found them online and took a chance. All the praise made sense after they helped us — now we're fans too." },
  { name: "Frank G.", place: "Omaha", avatar: "https://picsum.photos/seed/lw-r20/88/88", text: "Retired mechanic myself. These guys know what they're doing. I'd recommend to anyone." }
];
