window.LETS_WRENCH_REVIEWS = [
  { name: "Marcus T.", place: "Omaha", ago: "2 weeks ago", text: "Brakes were grinding on my Camry. Came to my apartment lot off 72nd, had it done in about 2 hours. Price matched the quote." },
  { name: "Linda R.", place: "Bellevue", ago: "1 month ago", text: "Battery died in the Hy-Vee lot when it was 8 degrees. They got out quick, tested the alternator too. Didn't miss my whole afternoon." },
  { name: "James P.", place: "Papillion", ago: "3 weeks ago", text: "Check engine light had me stressed. Explained the code without talking down to me. Fixed what actually needed fixing, not a bunch of extras." },
  { name: "Sarah M.", place: "Omaha", ago: "5 days ago", text: "Oil change in the driveway before work. On time, no mess, bill was what they said on the phone." },
  { name: "Danny K.", place: "La Vista", ago: "2 months ago", text: "Alternator died in the office parking garage. Fixed it in the stall so I didn't miss my shift." },
  { name: "Rachel H.", place: "Council Bluffs", ago: "6 weeks ago", text: "Pre-purchase inspection on a used F-150. Found rust and a bad ball joint the seller didn't mention. Saved me a headache." },
  { name: "Mike S.", place: "Omaha", ago: "4 days ago", text: "No-start at like 11pm. Someone actually picked up and showed up. Not gonna lie I didn't expect that." },
  { name: "Patricia W.", place: "Elkhorn", ago: "3 months ago", text: "Starter on my husband's Silverado. Quoted upfront, done same day in our driveway. Starts every time now." },
  { name: "Carlos G.", place: "Omaha", ago: "1 week ago", text: "Told me my rear brakes could wait a month. Another shop wanted to do them that day. Refreshing honesty." },
  { name: "Jennifer L.", place: "Bellevue", ago: "2 months ago", text: "We have 3 vans for our cleaning crew. They work around our routes and don't nickel and dime us." },
  { name: "Tom B.", place: "Omaha", ago: "5 weeks ago", text: "Weird rattling noise two shops couldn't figure out. Found a loose heat shield in ten minutes. Fixed on the spot." },
  { name: "Amy C.", place: "Papillion", ago: "3 days ago", text: "Tune up and plugs in the driveway. Runs smoother. Already called about my husband's SUV." },
  { name: "Robert N.", place: "Omaha", ago: "2 weeks ago", text: "Neighbor recommended them. Brother used them too. All good experiences so far." },
  { name: "Kelly D.", place: "La Vista", ago: "7 weeks ago", text: "Dealer wanted almost double for pads and rotors. These guys did it at my house for way less." },
  { name: "Steve F.", place: "Omaha", ago: "4 months ago", text: "Radiator hose blew near the I-80 exit. Met me in the Target lot and got me home safe." },
  { name: "Michelle A.", place: "Bellevue", ago: "10 days ago", text: "Sent a pic of a coolant leak, got a quote by text. Fixed it next morning before school drop off." },
  { name: "Brian E.", place: "Omaha", ago: "1 month ago", text: "Serpentine belt shredded in the Walmart lot on Dodge. New belt on in under an hour." },
  { name: "Diana J.", place: "Papillion", ago: "6 days ago", text: "Wheel bearing was humming bad on Cornhusker. Replaced in the driveway, test drove it with me after." },
  { name: "Greg O.", place: "Omaha", ago: "3 weeks ago", text: "You can tell they know Nebraska winters. Battery and coolant stuff they actually explain." },
  { name: "Natalie V.", place: "Council Bluffs", ago: "2 months ago", text: "Came to my job site over in CB and did my work truck during lunch. Didn't lose a day of pay." },
  { name: "Chris Z.", place: "Omaha", ago: "8 days ago", text: "Caught a cracked hose during a fluid check. Would've left me stranded later. Good catch." },
  { name: "Heather Q.", place: "Bellevue", ago: "5 weeks ago", text: "Thermostat and coolant flush at home. No sitting in a shop for 3 hours. Just done." },
  { name: "Tony M.", place: "Omaha", ago: "1 week ago", text: "Fair prices and they answer the phone. That's rare enough these days." },
  { name: "Vanessa R.", place: "La Vista", ago: "4 months ago", text: "AC died in July. Same day visit, cold air by dinner. Lifesaver with kids in the car." },
  { name: "Eric H.", place: "Omaha", ago: "3 months ago", text: "Looked at my daughter's first car before we bought it. Walked us through everything, zero pressure." },
  { name: "Sandra K.", place: "Papillion", ago: "2 weeks ago", text: "Flat tire and dead battery same morning. One trip, fixed both in the garage at work." },
  { name: "Justin W.", place: "Bellevue", ago: "9 days ago", text: "Texted for a quote, fair number back. Done in the driveway while I was on zoom calls." },
  { name: "Maria L.", place: "Omaha", ago: "1 month ago", text: "Single mom here — appreciated straight answers and no upsell talk. Car runs great." },
  { name: "David P.", place: "Elkhorn", ago: "6 weeks ago", text: "Four delivery vans. They keep us rolling without messing up our schedule." },
  { name: "Angela S.", place: "Omaha", ago: "3 days ago", text: "Turned out to be a loose gas cap lol. Still scanned everything and showed me the codes. Didn't charge me for drama." },
  { name: "Ryan T.", place: "La Vista", ago: "2 weeks ago", text: "Brakes at 8pm because I was scared to drive it. Showed up when they said they would." },
  { name: "Kim B.", place: "Bellevue", ago: "5 months ago", text: "Third time using them. Same quality every visit." },
  { name: "Oscar M.", place: "Omaha", ago: "11 days ago", text: "Work van behind our shop on L St. Back on the road same day." },
  { name: "Hannah F.", place: "Papillion", ago: "4 weeks ago", text: "Showed me photos of the bad alternator. Felt like I understood what I was paying for." },
  { name: "Trevor J.", place: "Council Bluffs", ago: "2 months ago", text: "Came across the river no problem. Price was still fair." },
  { name: "Brenda C.", place: "Omaha", ago: "7 weeks ago", text: "Fixed my dad's Buick in his driveway. Patient with him and left the area clean." },
  { name: "Luke A.", place: "La Vista", ago: "6 days ago", text: "Suspension clunk diagnosed fast. Parts same day. Solid." },
  { name: "Nicole D.", place: "Bellevue", ago: "3 weeks ago", text: "Found them online and took a chance. Glad I did — easy process start to finish." },
  { name: "Frank G.", place: "Omaha", ago: "2 months ago", text: "Retired mechanic. These guys know their stuff. Would send family to them." },
  { name: "DeShawn A.", place: "Omaha", ago: "4 days ago", text: "Quick." },
  { name: "Pam S.", place: "Gretna", ago: "1 week ago", text: "Came out to Gretna for a no-start. Battery and terminals. Under an hour total." }
];
